### init canvas
POST {{host}}/init?token={{token}}

### recovery canvas
POST  {{host}}/recovery?token={{token}}
Content-Type:  application/json

{
  "start": "1667985084",
  "end": "1676963455"
}

### put a pixel
PUT  {{host}}/pixels
Content-Type:  application/json

{
  "x": 50,
  "y": 50,
  "color": [255,0,0,255]
}

### get a pixel
GET  {{host}}/pixels?x=10&y=10

### get all pixels
GET  {{host}}/pixels/all

### sse pixel
GET  {{host}}/time
