spring:
  datasource:
    url: jdbc:sqlite:data.sqlite # for mysql jdbc:mysql://localhost:3306/app?createDatabaseIfNotExist=true
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  compression:
    enabled: true

app:
  width: 1000                                   # canvas width
  height: 1000                                  # canvas height
  backup-rate: 300                              # backup rate in seconds
  init-image: "init.png"                        # initial image path
  token: "cb2f4c23-5bfb-485c-aa65-e5873f279bab" # token for operation that requires authentication

debug: false
