name: Graalvm native build test
on: [pull_request, workflow_dispatch]
jobs:
  build-on-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: "22.3.0"
          java-version: "19"
          components: "native-image"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Gradle build
        run: ./gradlew nativeCompile

  build-on-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: "22.3.0"
          java-version: "19"
          components: "native-image"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Gradle build
        run: ./gradlew nativeCompile
